# Generated by Django 2.1.15 on 2020-04-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostinfomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sysadm_password', models.CharField(max_length=100)),
                ('zjgl_password', models.CharField(max_length=100)),
                ('cwgl_password', models.CharField(max_length=100)),
                ('root_password', models.CharField(max_length=100)),
                ('zbx_group', models.CharField(max_length=50)),
                ('machine_type', models.CharField(max_length=200)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hostinfomation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hostip',
            fields=[
                ('hostid', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=15)),
                ('hostname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hostip',
                'managed': False,
            },
        ),
    ]
